include:
  - project: 'ci-templates/mirror-to-github'  # Adjust path if needed
    file: 'mirror-to-github.yml'

stages:
  - mirror
  - deploy_prod

deploy_prod:
  stage: deploy_prod
  image: kroniak/ssh-client
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - echo "Deploying to Production..."
    - ssh maks@prod-node "cd /opt/docker/$CI_PROJECT_NAME && git pull origin main && docker compose up -d --build"
  when: manual
  only:
    - main